### PR TITLE
MDLSITE-4089 include records with blank countrycodes

### PR DESCRIPTION
**Pull request by k-holland**
After further discussion, syncing the stats and sites including all blank countrycodes

### CODE REVIEW

**Comment by mudrd8mz** [comment]
Thanks Karen. It does not matter here as we know this is running on MySQL, but ideally there should be `AS countrycode`. Also, I am wondering if there should stay `{$prefix}score > 3 AND` instead of the plain `score` without `{$prefix}`?

**Comment by k-holland** [comment]
Hi David, thanks for the feedback. For the "AS countrycode" insertion, is that meant for line 89 after "$sql = 'SELECT r.countrycode, "?

**Comment by mudrd8mz** [comment]
Sorry, did not want to confuse you :-) I am referring to the one before last item at https://docs.moodle.org/dev/SQL_coding_style#General_rules

> Always use AS keyword for column aliases.

At the line no. 44 of top/stats/lib.php there was originally

    COUNT(DISTINCT r.countrycode) countrycount

and ideally this alias should have been typed as

    COUNT(DISTINCT r.countrycode) AS countrycount

and similarly your new version should theoretically read

    COUNT(DISTINCT (case when r.countrycode <> \'\' then r.countrycode else \'AU\' end)) AS countrycount

But again, MySQL is tolerant to this so it does not matter. Also note that all other existing aliases in that file do not use AS, too. We tend to fail on our own coding guidelines for internal projects.

**Comment by k-holland** [comment]
Ok, added one further commit which deals with the column aliasing and adding the {$prefix} value back in as suggested, tia.

**Comment by mudrd8mz** [comment]
Thanks Karen.

**Pull request merged**
